CREATE DATABASE projectWork
    DEFAULT CHARACTER SET = 'utf8mb4';

USE projectWork;

CREATE TABLE users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    CreationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastAccessDate TIMESTAMP NULL,
    Active BOOLEAN DEFAULT FALSE
);


